detect.zsh collapsed into zshenv

diff --git a/zshcfg/zshenv b/zshcfg/zshenv
--- a/zshcfg/zshenv
+++ b/zshcfg/zshenv
@@ -7,14 +7,6 @@
 
 [ -d ~/dotfiles ] && export dotfiles=~/dotfiles || echo "Could not locate dotfiles at ~/dotfiles"
 
-# Autoloads 
-# See https://unix.stackexchange.com/questions/33255/how-to-define-and-load-your-own-shell-function-in-zsh
-#fpath=($dotfiles/zshcfg/zfuncs $fpath)
-#autoload -Uz detect_os determine_user
-
-source $dotfiles/zshcfg/zfuncs/detect.zsh
-
-
 main() {
   detect_os
   detect_user
@@ -31,7 +23,57 @@ main() {
   export MANPATH=":$dotfiles/man"
 }
 
+detect_os() {
+  uname=`uname`
+  if [[ $uname == 'Darwin' ]]; then
+    export isMacos=true
+  elif [[ $uname == 'Linux' ]]; then
+    export isLinux=true
+  elif [[ $uname == CYGWIN* ]]; then
+    export isCygwin=true
+  else
+    echo "This Setup Script only works for Windows Cygwin, Windows Subsystem for Linux and MacOS"
+    exit -1
+  fi
+  export osreleaseFile=/proc/sys/kernel/osrelease
+  if [[ -f  $osreleaseFile ]]; then
+    osrelease=`cat $osreleaseFile`
+    if [[ $osrelease == *Microsoft* ]]; then
+      export isWsl=true
+    fi
+  fi
+}
 
+get_windows_user() {
+	local sys32dir="/mnt/c/Windows/System32"
+	local winWho=$(cd $sys32dir; whoami.exe)
+	local winUser=${winWho##*\\}
+}
+
+detect_user() {
+  linUser=`whoami`
+  if [[ $isCygwin == true ]]; then
+    winUser=$linUser
+  fi
+
+  if [[ $isWsl == true ]]; then
+    winUser=$(get_windows_user)
+  fi
+}
+
+detect_util() {
+  hasCurl=$(command -v curl)
+  hasZip=$(command -v zip)
+  hasUnzip=$(command -v unzip)
+  hasGit=$(command -v git)
+  hasNeovim=$(command -v neovim)
+  [[ hasCurl ]] || echo "WARN: 'curl' not found. Setup may be incomplete"
+  [[ hasZip ]] || echo "WARN: 'zip' not found. Setup may be incomplete"
+  [[ hasUnzip ]] || echo "WARN: 'unzip' not found. Setup may be incomplete"
+  [[ hasGit ]] || echo "WARN: 'git' not found. Setup may be incomplete"
+  [[ hasNeovim ]] || echo "WARN: 'neovim' not found. Kindly install the same"
+  export done_detect_util=true
+}
 
 # Source ~/.env. ~/.env should export user/system
 # specific environment variables
